### ISSUE TITLE
Can not run `run_capture.bat`

### ISSUE THREAD

**Issue by saki4510t** [pupil-labs/pupil-docs#30]
Running `run_capture.bat` after following setup instruction in Developers Docs on Pupil Docs v0.9.4 and manually install `pyglui` from repository, it generates

```
C:\temp\pupil\pupil_src\capture>python main.py
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] world: Application Version: 0.9.4.16
world - [INFO] world: System Info: User: saki, Platform: Windows, Machine: Win10pro, Release: 10, Version: 10.0.14393
world - [INFO] pupil_detectors.build: Building extention modules...
cl : コマンド ライン warning D9025 : '/W3' より '/w' が優先されます。
cl : コマンド ライン warning D9002 : 不明なオプション '-std=c++11' を無視します
cl : コマンド ライン warning D9002 : 不明なオプション '-O3' を無視します
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
Process world:
Traceback (most recent call last):
  File "C:\Users\saki\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\saki\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\temp\pupil\pupil_src\capture\world.py", line 94, in world
    import pupil_detectors
  File "C:\temp\pupil\pupil_src\capture\pupil_detectors\__init__.py", line 16, in <module>
    build_cpp_extension()
  File "C:\temp\pupil\pupil_src\capture\pupil_detectors\build.py", line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd.format(sys.executable, install_loc), shell=True).decode(sys.stdout.encoding)
  File "C:\Users\saki\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "C:\Users\saki\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'C:\Users\saki\AppData\Local\Programs\Python\Python35\python.exe setup.py install --install-lib=C:\temp\pupil\pupil_src\capture' returned non-zero exit status 1
```

And can not run pupil capture.

**Comment by saki4510t** [comment]
wheel packages that I installed;

```
av-0.3.0-cp35-cp35m-win_amd64.whl
boost_python-1.63-cp35-cp35m-win_amd64.whl
Cython-0.25.2-cp35-cp35m-win_amd64.whl
ndsi-0.2.14-cp35-cp35m-win_amd64.whl
numpy-1.12.1+mkl-cp35-cp35m-win_amd64.whl
opencv_python-3.2.0-cp35-cp35m-win_amd64.whl
psutil-5.2.2-cp35-cp35m-win_amd64.whl
PyAudio-0.2.11-cp35-cp35m-win_amd64.whl
pyglui-1.2-cp35-cp35m-win_amd64.whl
PyOpenGL_accelerate-3.1.1-cp35-cp35m-win_amd64.whl
PyOpenGL-3.1.1-cp35-cp35m-win_amd64.whl
pyzmq-16.0.2-cp35-cp35m-win_amd64.whl
scipy-0.19.0-cp35-cp35m-win_amd64.whl
uvc-0.10-cp35-cp35m-win_amd64.whl
```

**Comment by saki4510t** [comment]
On above log, `cl.exe` returned exits status as 2 and that means "file not found", but what file does `cl.exe` can't find?

```
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
```

**Comment by saki4510t** [comment]
I set `/FC` command line option(to show full path name of source files) to `CL` environment variable but it seems to be ignored on building pupil capture.

**Comment by kktheballer** [comment]
@saki4510t Did you end up resolving this issue? If so, how did you fix it? I'm ripping the hair out of my head for this one.

**Comment by kirstymcnaught** [comment]
@kktheballer I'm having the same issue as you. One thing that helped track down _some_ path issues was to run: 
` DISTUTILS_DEBUG=1  python main.py`

This will tell you the exact compile command which failed, and then you can manually check that all the paths passed to it do indeed exist. This allowed me to fix a couple of incorrect include directories, but now I'm stuck with it expecting a PCbuild directory in my python install directory, which I do not have - possibly a cython install issue?

Let me know if you get further!

**Comment by willpatera** [comment]
Hi Windows people - We have updated windows development instructions for Pupil with Python36 and VS 2017 preview. I have verified that these instructions work on a clean machine (VM). Please see: https://docs.pupil-labs.com/master/#windows-dependencies

Please take a look at the updated instructions.
